### PR TITLE
Remove port from hostname

### PR DESCRIPTION
**Pull request by arkhan**
if the hostname has a port, for example, localhost:443, hostname is returned

### CODE REVIEW

**Comment by DamienCassou** [comment]
Thank you for your PR. Could you please add tests to the test suite to show what is expected? Also, please squash your commits into 1. Thank you.

**Comment by arkhan** [comment]
Hello,  I just added the tests

**Comment by DamienCassou** [comment]
Please rebase your branch on top of latest master. Please also make sure the Travis build passes.

**Comment by DamienCassou** [comment]
Can you please clean your PR? There are 5 commits now. Only 1 is necessary I guess.

**Pull request closed without merging**
