### PR TITLE
Find non-exactly matching hosts

### PR DESCRIPTION
**Pull request by DamienCassou**
Searching for "foo.bar.com" will now match "bar.com".

/cc @divansantana

### CODE REVIEW

**Comment by DamienCassou** [comment]
This should fix your IRC problem (part of issue 17). Please confirm. I will clean the code before merging.

**Comment by divansantana** [comment]
@DamienCassou Nice, quick patch! Though from my testing it seems not to be working as expected yet.

```
auth-password-store: searching for ’irc.freenode.net’ in entry names including user
auth-password-store: searching for ’freenode.net’ in entry names
auth-password-store: no entry name matched ’irc.freenode.net’, looking inside entries
auth-source-search: found 0 results (max 1) matching (:host "irc.freenode.net" :port "irc" :user "divansantana/freenode" :require (:user :secret))
Connecting to irc.freenode.net...
```

Basically, it says it's looking for `freenode.net` entry after failing to find `irc.freenode.net` though it doesn't find it and I can see it hanging emacs while it does a deep search in each and every pass entry.

**Comment by DamienCassou** [comment]
@divansantana sorry for the delay. Can you please tell me how to reproduce? What exactly do you have in your password store? Why are you sometimes referring to wilhelm.freenode.net and sometimes to irc.freenode.net?

**Comment by DamienCassou** [comment]
@divansantana I tried installing ERC and got a similar behavior. I have the impression that ERC:

1. authenticates with the server (`host=irc.freenode.net` and `user=yournick`)
2. and then authenticate with the channel (`host=rajaniemi.freenode.net` and `user=#emacs`)

For (1) to work, you need a password store entry named `freenode.net` or `irc.freenode.net` with this content:

```
thepassword
username: yournick in the server
```

I don't know why (2) is here, but it doesn't seem necessary. To avoid blocking Emacs while auth-password-store searches for a password for the channel, I removed the "looking inside entries" part (which is too slow to be any useful).

Can you please try the latest version in this branch and update your `freenode.net` password store entry?

**Comment by DamienCassou** [comment]
@divansantana could you please give me some feedback on this? I would like to continue working on this part of the code.

**Comment by divansantana** [comment]
@DamienCassou sorry for the delay in getting back to you.

I've tested and this seems to be working as expected now.

Details of my `init.el` file
```emacs-lisp
(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives '(			 
                         ("gnu"          . "https://elpa.gnu.org/packages/")
                         ("melpa"        . "https://melpa.org/packages/")
                         ))
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

  (use-package password-store
    :ensure t
    :pin melpa)
  (use-package auth-password-store
    :ensure t
    :load-path "/home/admin/git/github/auth-password-store"
    :config
    (setq auth-source-debug t)
  (auth-pass-enable))

(global-set-key "\C-cef" (lambda () (interactive)
                           (erc :server "irc.freenode.net" :port "6667"
                                :nick "divansantana")))
(setq erc-autojoin-channels-alist '(("freenode.net" "#emacs" "#parabola")))
```

Details of my pass
```
$ pass |grep freenode
├── freenode.net
$ pass show freenode.net
mypassword
user:divansantana
url:freenode.net
port:6667
```

Messages in the `*Messages*` buffer
```
git/github/auth-password-store/auth-password-store.el: Obsolete name arg "password-store" to constructor auth-source-backend
For information about GNU Emacs and the GNU system, type C-h C-a.
auth-password-store: searching for ’irc.freenode.net’ in entry names including user
auth-password-store: searching for ’freenode.net’ in entry names
auth-source-search: found 1 results (max 1) matching (:host "irc.freenode.net" :max 1 :user "divansantana" :port "6667" :require (:secret))
Connecting to irc.freenode.net:6667... ...done
Logging in as `divansantana'...
ERC: No process running [3 times]
Logging in as ‘divansantana’... done
auth-password-store: searching for ’asimov.freenode.net’ in entry names including user
auth-password-store: searching for ’freenode.net’ in entry names
auth-source-search: found 0 results (max 1) matching (:max 1 :host "asimov.freenode.net" :port "irc" :user "#emacs")
auth-password-store: searching for ’asimov.freenode.net’ in entry names including user
auth-password-store: searching for ’freenode.net’ in entry names
auth-source-search: found 0 results (max 1) matching (:max 1 :host "asimov.freenode.net" :port "irc" :user "#parabola")
auth-source-search: found 1 CACHED results matching (:host "irc.freenode.net" :max 1 :user "divansantana" :port "6667" :require (:secret)) [2 times]
```

It does login successfully and authenticate and auto login to the channels. So I'd say this is resolved and working great.

Thanks a lot!

**Comment by DamienCassou** [comment]
Merging that to a `next` branch for now.

**Pull request closed without merging**
